### ISSUE TITLE
Please improve question 2.1

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dataplan#37]
Improve version:
Where will you submit you data?

**Comment by xiaoranzhou** [comment]
I still think the current version:
"2.1 Where will you submit your data as endpoints?"
is better, because when the "endpoints" is missing, we must add other options such as PLANTDataHUB, GitHub, eLabFTW and so on.
If we need to change, I would also change it to "Where will you **archive your** data?"

**Comment by xiaoranzhou** [comment]
I will search for a better word

**Comment by xiaoranzhou** [comment]
Draft question:
2.1 Which archive will you submit your data to before publication?

**Comment by AngelaKranz** [comment]
To which archive will you submit your data?

Publication could also mean data publication, so this is misleading

**Comment by xiaoranzhou** [comment]
Is "To which archive will you submit your data before publishing the manuscript?" better?

Including "before publishing the manuscript" clarifies that the data submission is specifically related to the manuscript publication process, distinguishing it from other repositories like PLANTDataHUB or institutional storage.
