### ISSUE TITLE
Format and content of endpoint section

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/dataplan#4]
> Where will you submit your data as endpoints?
ENA, GEO, NCBI, genbank, pride, proteomexchange, zenodo, dataDyrad 
 ENA 
 GEO 
 NCBI 
 genbank 
 pride 
 proteomexchange 
 zenodo 
 dataDyrad

- the section misses numbering (format)
- repos are listed twice (one line + selection boxes) 
- selection of repositories could need improvement
  - GEO, genbank, proteomexchange are part of / link to NCBI, analogous repositories exist at EBI
- some data types listed in "2. What kind of data will you handle" are not really represented 
  - ideally repos could be deduced / suggested based on that

**Comment by xiaoranzhou** [comment]
> > Where will you submit your data as endpoints?
> > ENA, GEO, NCBI, genbank, pride, proteomexchange, zenodo, dataDyrad
> > ENA
> > GEO
> > NCBI
> > genbank
> > pride
> > proteomexchange
> > zenodo
> > dataDyrad
> 
> * the section misses numbering (format)
> * repos are listed twice (one line + selection boxes)
> * selection of repositories could need improvement
>   
>   * GEO, genbank, proteomexchange are part of / link to NCBI, analogous repositories exist at EBI
> * some data types listed in "2. What kind of data will you handle" are not really represented
>   
>   * ideally repos could be deduced / suggested based on that

1. the missed number is done by intention. Because it is an interactive element depends on the 
![image](https://user-images.githubusercontent.com/29843510/187232428-e68b6eb6-825d-41e8-bd00-e7dfedbac6f7.png)

Technicallly the renumbering of each interactive question is possibe, but I think it increase the code complexity without too much benefit and could potentially cause confusion.

2. The duplicated line is removed.
3. This part is an interactive element, the question will pop out if you will not use dataplant. Thus, question No.2 is also needed.
